### ISSUE TITLE
Feat: Add WAD repacking

### ISSUE THREAD

**Issue by NinjaCheetah** [NinjaCheetah/libWiiPy#11]
Now that a WAD can be fully unpacked with libWiiPy, the next step would be to repack it! This shouldn't be too hard, as it mostly just involves creating `set` variants of a lot of the current `get` methods in the ticket, TMD, content, and WAD classes.

**Comment by rvtr** [comment]
Sounds good. Just yaaaaay, how will the alignment affect repacking?

**Comment by NinjaCheetah** [comment]
I imagine for the most part it will probably just be doing the opposite of what the unpacking code does? I'd have to try to say for certain though.
